### ISSUE TITLE
simpler docker run 

### ISSUE THREAD

**Issue by streamnsight** [jin38324/OCI_GenAI_access_gateway#3]
if you use relative path to `~/.oci/keyfile` in the `.oci/config` file, you can simply mount the local .oci folder into `/root/.oci` and there is no need to move or copy keys.

also no need to mount the config.py and models/yaml since they are already copied into the image during build.

**Comment by jin38324** [comment]
Hi! Thanks for your comments!
Your point of view is correct and feasible, but I have some considerations.

1. **Mount the .oci folder is OK, but not recommended.**
Here is the reason:
Since the docker user is `root`, and the code use `~/.oci/config` to find the file, so you have to set the `key_file`  parameter in config file to `/root/.oci`. 
If the `.oci` folder not moved to `/root`, the two files will be conflicting for local users.
I prefer to keep the configuration valid, so I copy them to the right place.

2. **About config.py and models.yaml**
Users may set different parameters, for example API KEY,model name etc. 
I mount these files, so users can change the file and restart the docker to apply new settings, without build image again.

**Comment by streamnsight** [comment]
As I said in my comment, if you set your key path in the local `.oci/config` file to `key_file = ~/.oci/oci_api_key.pem` for example, it locally maps to your user (like `/Users/xyz/.oci/oci_api_key.pem`) when you mount it in a container at `/root/` and the container uses user `root`, then the local path for the container maps to `/root/.oci/`. There is no need to change anything and the oci SDK will pick up the config file and key location. I do this all the time. It works perfectly.

Copying keys in a container is a security issue. Especially if you are going to deploy on cloud, you want to use `INSTANCE_PRINCIPAL`, not keys, and you don't want to have an image with keys.

As for `model.yaml` and `config.py`, both are copied anyway on build, mounting them over the copied one is only useful if you made changes, which happens rarely. Rebuilding the image takes about 1.1sec on my machine. Not an issue to me, but much simpler to start the container without having to pass 2 extra volumes.

**Comment by jin38324** [comment]
Thanks for your explain! I will try and modify the read.me.
